// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlMUgcl1Ds2TFp2lwQS1NQCAW1A_RQpI',
    appId: '1:392799260162:web:deb76997676d5ff8d3211b',
    messagingSenderId: '392799260162',
    projectId: 'ksebea-8e7d8',
    authDomain: 'ksebea-8e7d8.firebaseapp.com',
    storageBucket: 'ksebea-8e7d8.firebasestorage.app',
    measurementId: 'G-CND0NE011V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Av5iy6Qk7EBO7MW_1-V5dcZ-ozdr7EA',
    appId: '1:392799260162:android:e49452fced179d2ad3211b',
    messagingSenderId: '392799260162',
    projectId: 'ksebea-8e7d8',
    storageBucket: 'ksebea-8e7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6yPOPiM-IJ6U8ikKUNT2rhlUmsT_Ky5Y',
    appId: '1:392799260162:ios:5310eb22bbbd019bd3211b',
    messagingSenderId: '392799260162',
    projectId: 'ksebea-8e7d8',
    storageBucket: 'ksebea-8e7d8.firebasestorage.app',
    iosBundleId: 'com.ksebea.in',
  );
}
